clusterGroup:
  test: 111
  foo:
    bandini1: 222
    bandini2: 456
    bandini3: 789
    bandini4: 000
    bandini5: 111
    baz: 234
    jobs:
      - name: foo
        playbook: foo.yml
      - name: bar
        playbook: bar.yml
