apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: basic
spec:
 server:
    route:
      enabled: true
 dex:
   openShiftOAuth: true
 rbac:
   defaultPolicy: 'role:readonly'
   policy: |
     g, system:cluster-admins, role:admin
   scopes: '[groups]'
